FROM python:3.13-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . ./backend
EXPOSE 8000
CMD ["uvicorn", "backend.route:app", "--host", "0.0.0.0", "--port", "8000"]
